import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import ChatWidget from "@/components/widget/chatwidget";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [openChat, setOpenChat] = useState(false);
  return (
    <>
      <Head>
        <title>Chat widget</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="chat-widget-container123">
        {openChat && (
          <main className="chat-widget123">
            <ChatWidget />
          </main>
        )}
        <button
          onClick={() => {
            setOpenChat(!openChat);
          }}
          className="chat-widget-button123"
        >
          {openChat ? "Close" : "Open"}
        </button>
      </div>
    </>
  );
}
